---
- name: Generate krb5.conf file.
  template:
    src: krb5.conf.j2
    dest: /usr/java/jre-vmware/lib/security/krb5.conf
    owner: root
    group: root
    mode: 0644
  register: krb5_conf_generated
