---
- name: "Get Catalog Object ID for {{ catalog_host }} in namespace {{ catalog_namespace }}"
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_api_port }}/vco/api/catalog/{{ catalog_namespace }}/"
    user: "{{ vro_temp_api_username }}"
    password: "{{ vro_temp_api_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: GET
    headers:
      Accept: "{{ http_Accept }}"
    http_agent: "{{ http_agent }}"
    status_code: [200]
  register: vro_catalog
  delegate_to: localhost

- name: "Set Catalog Object ID for: {{ catalog_host }}"
  set_fact:
    cat_object_id: "{{ (vro_catalog.json.relations | json_query(query) | first).split('/')[-2] }}"
  vars:
    query: "link[?attributes[?value == '{{ catalog_host }}']].href"
  when: vro_catalog.json.relations is defined
