---
- name: "Check if Package: {{ vro_package }} is installed."
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_api_port }}/vco/api/packages/{{ vro_package.split('.')[:-1] | join('.') }}"
    user: "{{ vro_api_username }}"
    password: "{{ vro_api_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: GET
    headers:
      Accept: "{{ http_Accept }}"
    status_code: [200, 404]
  register: vro_package_response
  delegate_to: localhost
  delegate_facts: true

- name: "Upload and Install Package: {{ vro_package }}"
  command: >
    curl -k -XPOST -u "{{ vro_api_username }}":"{{ vro_api_password }}"
    -H "Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__"
    -F "file=@{{ role_path }}/files/packages/{{ vro_package }}"
    https://{{ inventory_hostname|lower }}:{{ vro_api_port }}/vco/api/packages?overwrite=false&importConfigurationAttributeValues=true
  args:
    warn: false
  delegate_to: localhost
  register: vro_package_upload_response
  no_log: true
  when: |
    vro_package_response.status == 404 or
    vro_force_install_packages|bool