---
- name: "Setting vRO Service state to: {{ service_action }}"
  uri:
    url: "https://{{ inventory_hostname | lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/server/status/{{ service_action }}"
    user: "{{ vro_root_username }}"
    password: "{{ vro_root_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: POST
    headers:
      Accept: "{{ http_Accept }}"
    status_code: [200, 201]
  register: service_response
  delegate_to: localhost
