---
- name: Wait for vRO service to start
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/server/status"
    user: "{{ vro_root_username }}"
    password: "{{ vro_root_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: GET
    headers:
      Accept: "{{ http_Accept }}"
    status_code: [200, 400]
  register: response
  delegate_to: localhost
  delegate_facts: true
  until: response.status == 200 and response.json.currentStatus == "RUNNING"
  retries: 50
  delay: 10